sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - rpm
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  ~/.m2/settings.xml
- git clone --depth=50 --branch=2.0 https://github.com/Graylog2/graylog2-server.git  /home/travis/build/alcampos/graylog2-server
- cd /home/travis/build/alcampos/graylog2-server; git checkout tags/2.3.0;
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true; cd /home/travis/build/alcampos/graylog-plugin-alert-conditional-count
- echo "finished before_install"
- pwd
- ls
before_deploy:
- mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
- mvn rpm:rpm && export RELEASE_RPM_FILE=$(find target/ -name '*.rpm' | tail -1)
- rm -f target/original-*.jar
- export RELEASE_PKG_FILE=$(ls target/*.jar)
- echo "Deploying release to GitHub releases with the following files:"
- echo "$RELEASE_PKG_FILE"
- echo "$RELEASE_DEB_FILE"
- echo "$RELEASE_RPM_FILE"
deploy:
  provider: releases
  api_key:
    secure: xNXb0xsFgnkqBgWJgSzHnce4315Xk4ZI18UPZapHxVjGWhCBbjhh4CBNQc3n0t+iAb30OCHr8v2mFssHHXS2eN6Xewp91jrT1PWAhGcengzdW81VbEKx5cRoWpIRAplX4puKwYv1JCxX7MAOsjHA82X/oov7N1X43Yi9e9fIhpJ5xzeL81XWjWUUfVSAWznzoNxuOuw6a84wEm/5FYmyEpzphavzYZH6L4z21by4gwNXPoPeo1Qc7jTVGV9sih4Dwx+od4/RsWJa+0h//pjPaEh7kWok2jluIyam9SQZ+c3AskZ1bYC+18aICqqA+JlalScH/lCfo3o2MSawsIAmtkxVhH3nC8gW/afd6NR1FV6LrLFKZzYVA+G5Jxl2Y3ExcKfptrsOh/duzWE588ZX4K73V8D0yddSN/gCnCPabbiM/GXARgDWQ6A8rjK4qQ/DkmsqOeMkNoYPHSnJhCsC5+/Mvk2p2i8a/b6oo6UEG694DS8mYDewgnoDNVDnDbavpVhs/h524kapM8L0SuYw3i3bxItu3LGi5FUqgU6Yol4ZyUhUlhchfxLfLTx5o0sGwQmJ2pvGlCd2WxER/q9CQeofJLNQALkTPOWFFr6STLIgIDbgr8PWWKYGOL2oEXLSyFnq7AJJntCW6SdVkNJ1VunGmBizdqZKY/lFWA1wxg8=
  file:
    - "${RELEASE_PKG_FILE}"
    - "${RELEASE_DEB_FILE}"
    - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    repo: alcampos/graylog-plugin-alert-scheduled-conditional-count
    tags: true
